# A sample Gemfile
source "https://rubygems.org"

gem "sass", "3.2.12"
gem "compass", "0.12.2"
gem "singularitygs", "1.1.1"
gem "singularity-extras", "0.0.3"
gem "breakpoint", "2.0.7"
gem "bootstrap-sass", "3.0.0"
